/*
 * main.cpp
 *
 *  Created on: Aug 21, 2019
 *      Author: akadar
 *
 */

// Boost.Random uses deprecated boost/pending/integer_log2.hpp
// The following Macro disables it
# define BOOST_ALLOW_DEPRECATED_HEADERS

#include "complex.h"
#include <boost/version.hpp> 
#include <boost/random.hpp>

#include <ctime>

using namespace boost::random;

int main(){

    cx c;
    c.print_abs();

    std::cout << "Using Boost "
              << BOOST_VERSION / 100000     << "."  // major version
              << BOOST_VERSION / 100 % 1000 << "."  // minor version
              << BOOST_VERSION % 100                // patch level
              << std::endl;

    using uniform_int_dist = uniform_int_distribution<int>;
    uniform_int_dist dists;
    dists = uniform_int_dist(1,100);
    using RNG_mt19937 = mt19937;
    RNG_mt19937 rng_engine;
    rng_engine = RNG_mt19937(static_cast<unsigned>(std::time(0)));
    std::cout<<"Random int generated by Boost = "<<dists(rng_engine)<<"\n";

    return 0;
}
